version: '3'

services:
    app:
        image: product_review_webapp
        build:
            dockerfile: Dockerfile
        environment:
            - PORT=${PORT}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./ProductReviw:/ProductReviw